### ISSUE TITLE
Load Kibana objects from saved config files

### ISSUE THREAD

**Issue by mariusspielberger** [mariusspielberger/wwi15seb_se-project#20]
https://gist.github.com/turtlemonvh/36511794f7dff3bc9fd4156e0a29c5a1

**Comment by nZeloT** [comment]
added mini snapshot as start with arround 70 tweets; remember to see them you need to adjust the searchtime to include the whole day or even the day of creation;
everytime the container is build the snapshot inside the snapshot forlder is getting resored automatically;
there are instructions in the wiki on how to create a new snapshot
