### ISSUE TITLE
Spezifische Versionen in allen Komponenten

### ISSUE THREAD

**Issue by mariusspielberger** [mariusspielberger/wwi15seb_se-project#24]
Für ElasticSearch wurde bereits auf 5.5.0 geupdated, da es Probleme mit Kibana gab.

NodeRED wurde ebenfalls auf einen festen Versionsstand 0.16.2 gesetzt, da die join-Funktionalität nicht mehr funktioniert hat.

Es müssen alle Abhängigkeiten zu anderen Softwareversionen geprüft werden und jeweils eine konkrete Version angegeben werden, damit ein kompatibler Stack sichergestellt ist.

**Comment by nZeloT** [comment]
fixed versions to the latest avaliable at the moment
