### ISSUE TITLE
Dokumentation auf DockerHub erstellen

### ISSUE THREAD

**Issue by mariusspielberger** [mariusspielberger/wwi15seb_se-project#26]
Es soll eine Art Installationsanleitung sein, mit den Schritten, die zum erfolgreichen Aufsetzen des Stacks notwendig sind.

**Comment by mariusspielberger** [comment]
Konfiguration von zusätzlichen NodeRED-Flows, Kibana-Dashboards

**Comment by mariusspielberger** [comment]
Nummerierung auf DockerHub funktioniert nicht

**Comment by mariusspielberger** [comment]
Ein Anwendungsschritt pro Nummerierungspunkt

**Comment by annehaenzka** [comment]
Ist der Index in Kibana jetzt vorkonfiguriert?
