### ISSUE TITLE
HereAPI Test-Account anlegen (01.08.)

### ISSUE THREAD

**Issue by mariusspielberger** [mariusspielberger/wwi15seb_se-project#32]
Neuer Test-Account, den Reichwald dann 3 Monate lang nutzen kann

**Comment by inakolbinger** [comment]
AppID: ypp6hurRWQb4yxhLy2sp
AppCode: Qx6VM5MyBGjAwjfCry5PWQ

**Comment by mariusspielberger** [comment]
Done ;)
